# Make Bluetooth stronger
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable deep sleep
CONFIG_ZMK_SLEEP=y

# ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n
# CONFIG_ZMK_EXT_POWER=y

# 开启鼠标设备支持
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_KEYBOARD_NAME="Dpad6"
CONFIG_BT_DEVICE_NAME="Dpad6-BT"

# Enable Analog Input
CONFIG_ADC=y


# Enable debug logs
# CONFIG_LOG=y
# CONFIG_LOG_DEFAULT_LEVEL=4
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_ZMK_LOG_LEVEL_DBG=y
