manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: adminhxx
      url-base: https://github.com/adminhxx
  projects:
    - name: zmk
      remote: adminhxx
      revision: 34c5b3379c5d64b514307b74480c309f2d0b7f8d
      import: app/west.yml
  self:
    path: config
