# Make Bluetooth stronger
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable deep sleep
CONFIG_ZMK_SLEEP=y

# ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n
CONFIG_ZMK_EXT_POWER=y

# 开启鼠标设备支持
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_KEYBOARD_NAME="Dpad4"
CONFIG_BT_DEVICE_NAME="Dpad4-BT"

# Enable Analog Input
CONFIG_ADC=y

#RGB灯
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
# CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=n
# #断开usb默认关闭灯光
# CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y
# #默认亮度
# CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=50
# # 启用彩虹效果
# CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=2